// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rabbitmq/amqp091-go"
	"github.com/septian/worker-service/internal/config"
	"github.com/septian/worker-service/internal/repository"
	"github.com/septian/worker-service/internal/worker"
	"github.com/septian/worker-service/pkg/infrastructure"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

// InitializeWorker is the Wire injector function
func InitializeWorker() (*WorkerApp, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger()
	connection, err := infrastructure.NewRabbitMQConnection(configConfig, logger)
	if err != nil {
		return nil, err
	}
	channel, err := infrastructure.NewRabbitMQChannel(connection)
	if err != nil {
		return nil, err
	}
	client, err := infrastructure.NewElasticsearchClient(configConfig, logger)
	if err != nil {
		return nil, err
	}
	elasticsearchRepository := repository.NewElasticsearchRepository(client, configConfig, logger)
	showcaseConsumer := worker.NewShowcaseConsumer(channel, elasticsearchRepository, logger)
	workerApp := NewWorkerApp(configConfig, logger, connection, showcaseConsumer)
	return workerApp, nil
}

// wire.go:

// WorkerApp holds all dependencies for the worker service
type WorkerApp struct {
	Config   *config.Config
	Logger   *logrus.Logger
	MQConn   *amqp091.Connection
	Consumer *worker.ShowcaseConsumer
}

// NewWorkerApp creates a new WorkerApp instance
func NewWorkerApp(
	cfg *config.Config,
	log *logrus.Logger,
	conn *amqp091.Connection,
	consumer *worker.ShowcaseConsumer,
) *WorkerApp {
	return &WorkerApp{
		Config:   cfg,
		Logger:   log,
		MQConn:   conn,
		Consumer: consumer,
	}
}

// ProvideLogger provides a configured logrus logger
func ProvideLogger() *logrus.Logger {
	log := logrus.New()
	log.SetFormatter(&logrus.JSONFormatter{})
	log.SetLevel(logrus.InfoLevel)
	return log
}

// ProviderSet defines all providers for Wire
var ProviderSet = wire.NewSet(config.LoadConfig, ProvideLogger, infrastructure.NewRabbitMQConnection, infrastructure.NewRabbitMQChannel, infrastructure.NewElasticsearchClient, repository.NewElasticsearchRepository, worker.NewShowcaseConsumer, NewWorkerApp)
