# version: "3.8"

services:
  # ----------------------------------------------------------------
  # 1. DATABASE USER (PostgreSQL - Port 5432)
  # ----------------------------------------------------------------
  user_db:
    image: postgres:15-alpine
    container_name: talas_user_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: talas_user
    ports:
      - "5400:5432" # Host Port : Container Port
    volumes:
      - pg_data_user:/var/lib/postgresql/data
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 2. DATABASE CONTENT (PostgreSQL - Port 5433)
  # ----------------------------------------------------------------
  content_db:
    image: postgres:15-alpine
    container_name: talas_content_db
    restart: always
    environment:
      POSTGRES_USER: content_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: talas_content
    ports:
      - "5401:5432" # PENTING: Kita mapping port 5433 laptop ke 5432 container
    volumes:
      - pg_data_content:/var/lib/postgresql/data
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 3. CACHE (Redis - Port 6379)
  # ----------------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: talas_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 4. MESSAGE BROKER (RabbitMQ - Port 5672 & 15672)
  # ----------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: talas_rabbitmq
    restart: always
    ports:
      - "5672:5672" # Port komunikasi antar service
      - "15672:15672" # Port Dashboard UI (Buka di browser)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 5. SEARCH ENGINE (Elasticsearch - Port 9200)
  # ----------------------------------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: talas_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - talas_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: talas_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 6. API GATEWAY (Nginx - Port 80)
  # ----------------------------------------------------------------
  gateway:
    image: nginx:alpine
    container_name: talas_gateway
    restart: always
    ports:
      - "82:80" # Port 82 Laptop -> Port 80 Container
    volumes:
      # Mount file config dari laptop ke dalam container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      # PENTING: Agar container bisa memanggil 'localhost' laptop kamu
      - "host.docker.internal:host-gateway"
    networks:
      - talas_network

  # ----------------------------------------------------------------
  # 7. USER SERVICE (Node.js - Port 3001)
  # ----------------------------------------------------------------
  user_service:
    build: ./user-service # Arahkan ke folder user-service
    container_name: talas_user_service
    restart: always
    ports:
      - "3001:3001"
    # 1. Baca secret umum dari file .env (JWT_SECRET, INTERNAL_SECRET, dll)
    env_file:
      - ./user-service/.env
    # 2. TAPI, paksa ganti URL koneksi agar cocok dengan jaringan Docker
    # (Docker akan memprioritaskan nilai di bawah ini daripada yang ada di file .env)
    environment:
      - DATABASE_URL=postgresql://user_admin:password123@user_db:5432/talas_user?schema=public
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - PORT=3001
      - INTERNAL_SERVICE_SECRET="rahasia-dapur-talas-microservices-2026"
    depends_on:
      user_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - talas_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maksimal 1 file log 10MB
        max-file: "3" # Simpan maksimal 3 file terakhir (Rolling)

  # ----------------------------------------------------------------

  # 8. CONTENT SERVICE (Go - Port 3002)
  # ----------------------------------------------------------------
  content_service:
    build: ./content-service
    container_name: talas_content_service
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./content-service/.env
    environment:
      - DB_HOST=content_db
      - DB_PORT=5432
      - REDIS_URL=redis:6379
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - USER_SERVICE_URL=http://user_service:3001
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      content_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      user_service:
        condition: service_started
    networks:
      - talas_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Maksimal 1 file log 10MB
        max-file: "3" # Simpan maksimal 3 file terakhir (Rolling)

  # ----------------------------------------------------------------
  # 9. WORKER SERVICE (Go Worker)
  # ----------------------------------------------------------------
  worker_service:
    build: ./worker-service
    container_name: talas_worker_service
    restart: always
    env_file:
      - ./worker-service/.env
    environment:
      - DB_HOST=content_db
      - DB_PORT=5432
      - REDIS_URL=redis:6379
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - USER_SERVICE_URL=http://user_service:3001
      - CONTENT_SERVICE_URL=http://content_service:3002
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - USER_DATABASE_URL=postgresql://user_admin:password123@user_db:5432/talas_user?sslmode=disable
    depends_on:
      content_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      user_service:
        condition: service_started
    networks:
      - talas_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Definisi Volume (Agar data tidak hilang saat container mati)
volumes:
  pg_data_user:
  pg_data_content:
  redis_data:
  elastic_data:

# Definisi Network (Jalan raya khusus container)
networks:
  talas_network:
    driver: bridge
