// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/septianpadli/talas/content-service/internal/config"
	"github.com/septianpadli/talas/content-service/internal/handler"
	"github.com/septianpadli/talas/content-service/internal/repository"
	"github.com/septianpadli/talas/content-service/internal/usecase"
	"github.com/septianpadli/talas/content-service/pkg/database"
	"github.com/septianpadli/talas/content-service/pkg/logger"
	"github.com/septianpadli/talas/content-service/pkg/middleware"
)

// Injectors from wire.go:

// Ini adalah fungsi yang akan kita panggil di main.go
// Wire akan otomatis mengisi return value-nya (misal *fiber.App)
func InitializeApp() (*fiber.App, error) {
	configConfig := config.LoadConfig()
	db := database.ConnectDB(configConfig)
	showcaseRepository := repository.NewShowcaseRepository(db)
	logrusLogger := logger.NewLogger()
	showcaseUsecase := usecase.NewShowcaseUsecase(showcaseRepository, configConfig, logrusLogger)
	showcaseHandler := handler.NewShowcaseHandler(showcaseUsecase)
	authMiddleware := middleware.NewAuthMiddleware(configConfig)
	app := NewFiberApp(db, showcaseHandler, authMiddleware, logrusLogger)
	return app, nil
}
