// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/septianpadli/talas/content-service/internal/config"
	"github.com/septianpadli/talas/content-service/internal/handler"
	"github.com/septianpadli/talas/content-service/internal/repository"
	"github.com/septianpadli/talas/content-service/internal/usecase"
	"github.com/septianpadli/talas/content-service/pkg/clients"
	"github.com/septianpadli/talas/content-service/pkg/database"
	"github.com/septianpadli/talas/content-service/pkg/infrastructure"
	"github.com/septianpadli/talas/content-service/pkg/logger"
	"github.com/septianpadli/talas/content-service/pkg/media"
	"github.com/septianpadli/talas/content-service/pkg/middleware"
	"github.com/septianpadli/talas/content-service/pkg/rabbitmq"
)

// Injectors from wire.go:

// Ini adalah fungsi yang akan kita panggil di main.go
// Wire akan otomatis mengisi return value-nya (misal *fiber.App)
func InitializeApp() (*fiber.App, error) {
	configConfig := config.LoadConfig()
	db := database.ConnectDB(configConfig)
	logrusLogger := logger.NewLogger()
	client, err := infrastructure.NewRedisClient(configConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	showcaseRepository := repository.NewShowcaseRepository(db)
	elasticsearchClient, err := infrastructure.NewElasticsearchClient(configConfig)
	if err != nil {
		return nil, err
	}
	searchRepository := repository.NewSearchRepository(elasticsearchClient, configConfig, logrusLogger)
	userClient := clients.NewUserClient(configConfig, logrusLogger)
	cloudinaryUploader, err := media.NewCloudinaryUploader(configConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	eventPublisher := rabbitmq.NewRabbitMQPublisher(configConfig, logrusLogger)
	showcaseUsecase := usecase.NewShowcaseUsecase(showcaseRepository, searchRepository, userClient, cloudinaryUploader, eventPublisher, client, configConfig, logrusLogger)
	showcaseHandler := handler.NewShowcaseHandler(showcaseUsecase, logrusLogger)
	internalHandler := handler.NewInternalHandler(showcaseUsecase, userClient, logrusLogger)
	categoryRepository := repository.NewCategoryRepository(db)
	categoryUsecase := usecase.NewCategoryUsecase(categoryRepository)
	categoryHandler := handler.NewCategoryHandler(categoryUsecase)
	commentRepository := repository.NewCommentRepository(db)
	commentUsecase := usecase.NewCommentUsecase(commentRepository, searchRepository, showcaseRepository, userClient, eventPublisher, configConfig, logrusLogger)
	commentHandler := handler.NewCommentHandler(commentUsecase, logrusLogger)
	collabRepository := repository.NewCollabRepository(db)
	collabUsecase := usecase.NewCollabUsecase(showcaseRepository, collabRepository, searchRepository, userClient, cloudinaryUploader, eventPublisher, client, configConfig, logrusLogger)
	collabHandler := handler.NewCollabHandler(collabUsecase, logrusLogger)
	handlerGroup := NewHandlerGroup(showcaseHandler, internalHandler, categoryHandler, commentHandler, collabHandler)
	authMiddleware := middleware.NewAuthMiddleware(configConfig)
	app := NewFiberApp(db, client, configConfig, handlerGroup, authMiddleware, logrusLogger)
	return app, nil
}
